// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CaptureHotkey():Promise<string>;

export function ClearHistory():Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetHistory():Promise<Array<main.HistoryEntry>>;

export function GetState():Promise<string>;

export function ListInputDevices():Promise<Array<main.AudioDevice>>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function ToggleRecording():Promise<void>;

export function ValidateHotkey(arg1:string):Promise<string>;
