// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function ListInputDevices() {
  return window['go']['main']['App']['ListInputDevices']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ToggleRecording() {
  return window['go']['main']['App']['ToggleRecording']();
}

export function ValidateHotkey(arg1) {
  return window['go']['main']['App']['ValidateHotkey'](arg1);
}
